{
 "title": "AESO - Status",
 "description": "Alberta Electric System Operator - Supply Demand",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Pool Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(poolprice)" }
   ]
  },
  {
   "title": "Current Net Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(tng_stats)" }
   ]
  },
  {
   "title": "Interchange Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-interchange{location=\"total\"}"
    }
   ]
  },
  {
   "title": "Alberta Internal Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats >= 0)-sum(interchange{location=\"total\"})"
    }
   ]
  },
  {
   "title": "Alberta Internal Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats >= 0)/sum(mc_stats >= 0)"
    }
   ]
  },
  {
   "title": "Energy Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(dcr_stats{type=\"energy_storage\"})"
    }
   ]
  },
  {
   "title": "Coal Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"coal\"})/sum(mc_stats{type=\"coal\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"gas\"} >= 0)/sum(mc_stats{type=\"gas\"} >= 0)"
    }
   ]
  },
  {
   "title": "Wind Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"wind\"})/sum(mc_stats{type=\"wind\"})"
    }
   ]
  },
  {
   "title": "Hydro Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"hydro\"})/sum(mc_stats{type=\"hydro\"})"
    }
   ]
  },
  {
   "title": "Solar Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"solar\"})/sum(mc_stats{type=\"solar\"})"
    }
   ]
  },
  {
   "title": "Other Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"biomass_and_other\"})/sum(mc_stats{type=\"biomass_and_other\"})"
    }
   ]
  },
  {
   "title": "Asset Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tng_stats", "legendFormat": "{{asset}}" }
   ]
  },
  {
   "title": "Pool Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "poolprice", "legendFormat": "Price" }
   ]
  },
  {
   "title": "Current Market Value ($/h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(generation_tng) without(group,instance,job)  * sum(poolprice) without(instance,job)"
    }
   ]
  },
  {
   "title": "Energy Interchange",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "interchange{location!=\"TOTAL\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Net Electricity Generation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    { "expr": "sum(tng_stats >=0)", "legendFormat": "Net Generation" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperatures for Major Cities in Alberta",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "round(temperature{city=\"Calgary\",feels_like=\"\"})",
     "legendFormat": "{{city}}"
    },
    {
     "expr": "round(temperature{city=\"Edmonton\",feels_like=\"\"})",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Total Net Generation By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"coal\"} > 0)",
     "legendFormat": "Coal"
    },
    {
     "expr": "sum(tng_stats{type=\"wind\"} > 0)",
     "legendFormat": "Wind"
    },
    {
     "expr": "sum(tng_stats{type=\"gas\"} > 0)",
     "legendFormat": "Gas"
    },
    {
     "expr": "sum(tng_stats{type=\"hydro\"} > 0)",
     "legendFormat": "Hydro"
    },
    {
     "expr": "sum(tng_stats{type=\"biomass_and_other\"} > 0)",
     "legendFormat": "Biomass/Other"
    },
    {
     "expr": "sum(tng_stats{type=\"solar\"} > 0)",
     "legendFormat": "Solar"
    },
    {
     "expr": "sum(tng_stats{type=\"dual_fuel\"} > 0)",
     "legendFormat": "Dual Fuel"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar- Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "sum(mc_stats{type=\"solar\"} >= 0)",
       "legendFormat": "Max Capacity"
      },
      {
       "expr": "sum(tng_stats{type=\"solar\"} >= 0)",
       "legendFormat": "Generated"
      },
      {
       "expr": "sum(dcr_stats{type=\"solar\"} >= 0)",
       "legendFormat": "Dispatched Contingency Reserve"
      }
     ]
    },
    {
     "title": "Solar- Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"solar\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hydro",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hydro - Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "sum(mc_stats{type=\"hydro\"} >= 0)",
       "legendFormat": "Max Capacity"
      },
      {
       "expr": "sum(tng_stats{type=\"hydro\"} >= 0)",
       "legendFormat": "Generated"
      },
      {
       "expr": "sum(dcr_stats{type=\"hydro\"} >= 0)",
       "legendFormat": "Dispatched Contingency Reserve"
      }
     ]
    },
    {
     "title": "Hydro - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"hydro\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Coal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coal - Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "sum(mc_stats{type=\"coal\"} >= 0)",
       "legendFormat": "Max Capacity"
      },
      {
       "expr": "sum(tng_stats{type=\"coal\"} >= 0)",
       "legendFormat": "Generated"
      },
      {
       "expr": "sum(dcr_stats{type=\"coal\"} >= 0)",
       "legendFormat": "Dispatched Contingency Reserve"
      }
     ]
    },
    {
     "title": "Coal - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"coal\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wind",
     "type": "timeseries",
     "description": "Wind for Major Cities in Alberta",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      { "expr": "wind", "legendFormat": "{{city}}" }
     ]
    },
    {
     "title": "Wind - Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "sum(mc_stats{type=\"wind\"} >= 0)",
       "legendFormat": "Max Capacity"
      },
      {
       "expr": "sum(tng_stats{type=\"wind\"} >= 0)",
       "legendFormat": "Generated"
      },
      {
       "expr": "sum(dcr_stats{type=\"wind\"} >= 0)",
       "legendFormat": "Dispatched Contingency Reserve"
      }
     ]
    },
    {
     "title": "Wind - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"wind\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gas - Overview",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "sum(mc_stats{type=\"gas\"} >= 0)",
       "legendFormat": "Max Capacity"
      },
      {
       "expr": "sum(tng_stats{type=\"gas\"} >= 0)",
       "legendFormat": "Generated"
      },
      {
       "expr": "sum(dcr_stats{type=\"gas\"} >= 0)",
       "legendFormat": "Dispatched Contingency Reserve"
      }
     ]
    },
    {
     "title": "Gas - Simple Cycle - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"gas\",category=\"Simple\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    },
    {
     "title": "Gas - Cogeneration - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"gas\",category=\"Cogeneration\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    },
    {
     "title": "Gas - Combined- Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"gas\",category=\"Combined\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    },
    {
     "title": "Gas - Gas Fired Steam - Generated Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "megwatt" } },
     "targets": [
      {
       "expr": "tng_stats{type=\"gas\",category=\"Gas Fired Steam\"} > 0",
       "legendFormat": "{{asset}}"
      }
     ]
    }
   ]
  }
 ]
}