{
 "title": "Energy Type Breakdown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "query": {
     "query": "label_values({__name__=~\"tng_.*\"},type)"
    }
   },
   {
    "name": "tng_stats",
    "query": {
     "query": "query_result(tng_stats{asset=~\"$asset\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of $type Plants",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(tng_stats{type='$type'})" }
   ]
  },
  {
   "title": "$type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"$type\"}) / sum(tng_stats)"
    }
   ]
  },
  {
   "title": "Total $type Production",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"$type\"})"
    }
   ]
  },
  {
   "title": "Total Net Generated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "sum(tng_stats{type=\"$type\"})",
     "legendFormat": "Total Net Generation"
    },
    {
     "expr": "sum(mc_stats{type=\"$type\"})",
     "legendFormat": "Max Capacity"
    }
   ]
  },
  {
   "title": "Top 10 $type Plants",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,tng_stats{type=\"$type\"})",
     "legendFormat": "{{asset}}"
    }
   ]
  }
 ]
}